#!/bin/bash
# sync-skills.sh — Regenerates the top-level skills/ mirror from the
# canonical plugins/<plugin>/skills/<skill>/SKILL.md files.
#
# Usage:
#   bash scripts/sync-skills.sh           # regenerate skills/
#   bash scripts/sync-skills.sh --check   # exit 1 if skills/ is stale (for CI / pre-commit)
#
# Why: users who want to *read* or *adopt* a skill without running /plugin install
# can browse the flat skills/ tree at the repo root. Source of truth stays in
# plugins/, so edits always go there and the mirror is regenerated.

set -e

MODE="${1:-regenerate}"

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PLUGINS_DIR="$ROOT/plugins"
SKILLS_DIR="$ROOT/skills"

if [ ! -d "$PLUGINS_DIR" ]; then
  echo "❌ No plugins/ directory found at $PLUGINS_DIR"
  exit 1
fi

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

STAGING="$TEMP_DIR/skills"
mkdir -p "$STAGING"

ENTRIES=()

for plugin_skills_dir in "$PLUGINS_DIR"/*/skills; do
  [ -d "$plugin_skills_dir" ] || continue
  plugin_name="$(basename "$(dirname "$plugin_skills_dir")")"

  for skill_dir in "$plugin_skills_dir"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    src="$skill_dir/SKILL.md"
    [ -f "$src" ] || continue

    dest_dir="$STAGING/${plugin_name}__${skill_name}"
    mkdir -p "$dest_dir"
    dest="$dest_dir/SKILL.md"

    {
      echo "<!--"
      echo "This file is auto-generated by scripts/sync-skills.sh."
      echo "Canonical source: plugins/${plugin_name}/skills/${skill_name}/SKILL.md"
      echo "Do NOT edit here. Edit the canonical source and re-run scripts/sync-skills.sh."
      echo "-->"
      cat "$src"
    } > "$dest"

    # Copy any sibling files (e.g. supporting templates) alongside SKILL.md
    for extra in "$skill_dir"*; do
      base="$(basename "$extra")"
      if [ "$base" != "SKILL.md" ] && [ -f "$extra" ]; then
        cp "$extra" "$dest_dir/$base"
      fi
    done

    desc="$(awk '/^description:/{ sub(/^description:[[:space:]]*/, ""); print; exit }' "$src")"
    ENTRIES+=("${plugin_name}__${skill_name}|${plugin_name}|${skill_name}|${desc}")
  done
done

# Generate README.md index, sorted by plugin then skill
{
  echo "# Skills Index"
  echo ""
  echo "> Auto-generated by \`scripts/sync-skills.sh\` from \`plugins/*/skills/*/SKILL.md\`."
  echo "> **Do not edit files here.** Edit the canonical source in \`plugins/\` and re-run the sync."
  echo ""
  echo "Each row links to the mirrored \`SKILL.md\`. The canonical file is listed in each mirror's header banner."
  echo ""
  echo "| Plugin | Skill | Description |"
  echo "|---|---|---|"
} > "$STAGING/README.md"

if [ ${#ENTRIES[@]} -gt 0 ]; then
  printf '%s\n' "${ENTRIES[@]}" | sort | while IFS='|' read -r dir plugin skill desc; do
    # Escape pipe chars in description so they don't break the table
    safe_desc="${desc//|/\\|}"
    printf '| `%s` | [`%s`](./%s/SKILL.md) | %s |\n' "$plugin" "$skill" "$dir" "$safe_desc" >> "$STAGING/README.md"
  done
fi

# Check mode: compare and exit
if [ "$MODE" = "--check" ]; then
  if [ ! -d "$SKILLS_DIR" ]; then
    echo "❌ skills/ directory missing. Run: bash scripts/sync-skills.sh"
    exit 1
  fi
  if ! diff -rq "$SKILLS_DIR" "$STAGING" > /dev/null 2>&1; then
    echo "❌ skills/ is out of date. Run: bash scripts/sync-skills.sh"
    diff -r "$SKILLS_DIR" "$STAGING" || true
    exit 1
  fi
  echo "✅ skills/ is in sync."
  exit 0
fi

# Regenerate mode: replace skills/ with staging
rm -rf "$SKILLS_DIR"
mkdir -p "$SKILLS_DIR"
cp -R "$STAGING"/. "$SKILLS_DIR"/

count="$(find "$SKILLS_DIR" -name "SKILL.md" | wc -l | tr -d ' ')"
echo "✅ skills/ regenerated — $count skill(s) mirrored."
