#!/bin/bash
# sync-skills.sh — Regenerates the top-level skills/ and agents/ mirrors
# from the canonical plugins/<plugin>/skills/<skill>/SKILL.md and
# plugins/<plugin>/agents/<agent>.md files.
#
# Usage:
#   bash scripts/sync-skills.sh           # regenerate mirrors
#   bash scripts/sync-skills.sh --check   # exit 1 if mirrors are stale
#
# Why: users who want to *read* or *adopt* a skill / subagent without
# running /plugin install can browse the flat skills/ and agents/ trees
# at the repo root. Source of truth stays in plugins/; edits go there
# and the mirror is regenerated.

set -e

MODE="${1:-regenerate}"

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PLUGINS_DIR="$ROOT/plugins"
SKILLS_DIR="$ROOT/skills"
AGENTS_DIR="$ROOT/agents"

if [ ! -d "$PLUGINS_DIR" ]; then
  echo "❌ No plugins/ directory found at $PLUGINS_DIR"
  exit 1
fi

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

STAGING_SKILLS="$TEMP_DIR/skills"
STAGING_AGENTS="$TEMP_DIR/agents"
mkdir -p "$STAGING_SKILLS" "$STAGING_AGENTS"

SKILL_ENTRIES=()
AGENT_ENTRIES=()

# ---- Skills sync ----------------------------------------------------------
for plugin_skills_dir in "$PLUGINS_DIR"/*/skills; do
  [ -d "$plugin_skills_dir" ] || continue
  plugin_name="$(basename "$(dirname "$plugin_skills_dir")")"

  for skill_dir in "$plugin_skills_dir"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    src="$skill_dir/SKILL.md"
    [ -f "$src" ] || continue

    dest_dir="$STAGING_SKILLS/${plugin_name}__${skill_name}"
    mkdir -p "$dest_dir"
    dest="$dest_dir/SKILL.md"

    {
      echo "<!--"
      echo "This file is auto-generated by scripts/sync-skills.sh."
      echo "Canonical source: plugins/${plugin_name}/skills/${skill_name}/SKILL.md"
      echo "Do NOT edit here. Edit the canonical source and re-run scripts/sync-skills.sh."
      echo "-->"
      cat "$src"
    } > "$dest"

    for extra in "$skill_dir"*; do
      base="$(basename "$extra")"
      if [ "$base" != "SKILL.md" ] && [ -f "$extra" ]; then
        cp "$extra" "$dest_dir/$base"
      fi
    done

    desc="$(awk '/^description:/{ sub(/^description:[[:space:]]*/, ""); print; exit }' "$src")"
    SKILL_ENTRIES+=("${plugin_name}__${skill_name}|${plugin_name}|${skill_name}|${desc}")
  done
done

# ---- Agents sync ----------------------------------------------------------
for plugin_agents_dir in "$PLUGINS_DIR"/*/agents; do
  [ -d "$plugin_agents_dir" ] || continue
  plugin_name="$(basename "$(dirname "$plugin_agents_dir")")"

  for agent_file in "$plugin_agents_dir"/*.md; do
    [ -f "$agent_file" ] || continue
    agent_name="$(basename "$agent_file" .md)"

    dest="$STAGING_AGENTS/${plugin_name}__${agent_name}.md"

    {
      echo "<!--"
      echo "This file is auto-generated by scripts/sync-skills.sh."
      echo "Canonical source: plugins/${plugin_name}/agents/${agent_name}.md"
      echo "Do NOT edit here. Edit the canonical source and re-run scripts/sync-skills.sh."
      echo "-->"
      cat "$agent_file"
    } > "$dest"

    desc="$(awk '/^description:/{ sub(/^description:[[:space:]]*/, ""); print; exit }' "$agent_file")"
    AGENT_ENTRIES+=("${plugin_name}__${agent_name}|${plugin_name}|${agent_name}|${desc}")
  done
done

# ---- Index generation -----------------------------------------------------
{
  echo "# Skills Index"
  echo ""
  echo "> Auto-generated by \`scripts/sync-skills.sh\` from \`plugins/*/skills/*/SKILL.md\`."
  echo "> **Do not edit files here.** Edit the canonical source in \`plugins/\` and re-run the sync."
  echo ""
  if [ ${#SKILL_ENTRIES[@]} -eq 0 ]; then
    echo "_No skills found._"
  else
    echo "| Plugin | Skill | Description |"
    echo "|---|---|---|"
  fi
} > "$STAGING_SKILLS/README.md"

if [ ${#SKILL_ENTRIES[@]} -gt 0 ]; then
  printf '%s\n' "${SKILL_ENTRIES[@]}" | sort | while IFS='|' read -r dir plugin skill desc; do
    safe_desc="${desc//|/\\|}"
    printf '| `%s` | [`%s`](./%s/SKILL.md) | %s |\n' "$plugin" "$skill" "$dir" "$safe_desc" >> "$STAGING_SKILLS/README.md"
  done
fi

{
  echo "# Subagents Index"
  echo ""
  echo "> Auto-generated by \`scripts/sync-skills.sh\` from \`plugins/*/agents/*.md\`."
  echo "> **Do not edit files here.** Edit the canonical source in \`plugins/\` and re-run the sync."
  echo ""
  if [ ${#AGENT_ENTRIES[@]} -eq 0 ]; then
    echo "_No subagents found._"
  else
    echo "| Plugin | Subagent | Description |"
    echo "|---|---|---|"
  fi
} > "$STAGING_AGENTS/README.md"

if [ ${#AGENT_ENTRIES[@]} -gt 0 ]; then
  printf '%s\n' "${AGENT_ENTRIES[@]}" | sort | while IFS='|' read -r dir plugin agent desc; do
    safe_desc="${desc//|/\\|}"
    printf '| `%s` | [`%s`](./%s.md) | %s |\n' "$plugin" "$agent" "$dir" "$safe_desc" >> "$STAGING_AGENTS/README.md"
  done
fi

# ---- Check / regenerate ---------------------------------------------------
if [ "$MODE" = "--check" ]; then
  stale=0

  if [ ! -d "$SKILLS_DIR" ]; then
    echo "❌ skills/ directory missing. Run: bash scripts/sync-skills.sh"
    stale=1
  elif ! diff -rq "$SKILLS_DIR" "$STAGING_SKILLS" > /dev/null 2>&1; then
    echo "❌ skills/ is out of date. Run: bash scripts/sync-skills.sh"
    diff -r "$SKILLS_DIR" "$STAGING_SKILLS" || true
    stale=1
  fi

  # agents/ is only required when there are agent entries to mirror
  if [ ${#AGENT_ENTRIES[@]} -gt 0 ]; then
    if [ ! -d "$AGENTS_DIR" ]; then
      echo "❌ agents/ directory missing. Run: bash scripts/sync-skills.sh"
      stale=1
    elif ! diff -rq "$AGENTS_DIR" "$STAGING_AGENTS" > /dev/null 2>&1; then
      echo "❌ agents/ is out of date. Run: bash scripts/sync-skills.sh"
      diff -r "$AGENTS_DIR" "$STAGING_AGENTS" || true
      stale=1
    fi
  fi

  if [ "$stale" -eq 0 ]; then
    echo "✅ Mirrors are in sync."
    exit 0
  else
    exit 1
  fi
fi

# Regenerate mode
rm -rf "$SKILLS_DIR"
mkdir -p "$SKILLS_DIR"
cp -R "$STAGING_SKILLS"/. "$SKILLS_DIR"/

if [ ${#AGENT_ENTRIES[@]} -gt 0 ]; then
  rm -rf "$AGENTS_DIR"
  mkdir -p "$AGENTS_DIR"
  cp -R "$STAGING_AGENTS"/. "$AGENTS_DIR"/
else
  rm -rf "$AGENTS_DIR"
fi

skill_count="$(find "$SKILLS_DIR" -name "SKILL.md" | wc -l | tr -d ' ')"
agent_count=0
if [ -d "$AGENTS_DIR" ]; then
  agent_count="$(find "$AGENTS_DIR" -maxdepth 1 -name "*.md" -not -name "README.md" | wc -l | tr -d ' ')"
fi
echo "✅ Mirrors regenerated — $skill_count skill(s), $agent_count subagent(s)."
